### ISSUE TITLE
A bunch of things to do with beds not being dropped, shulker boxes losing functionality, and some debug and easy way to check transformations

### ISSUE THREAD

**Issue by sapioit** [Fasguy/sb-ltr#1]
Basically, there are 3 issues I see with this:

I think beds should have the normal functionality, because they cannot get dropped by mobs (it gets if both halves of the bed are there, before dropping). 

I think shulker boxes should keep their original drop table, so we can still use them for portable storage.

There are 21 or so items which do not drop anything (excluding the beds which check for halves), which I thick could be used to first drop shulker boxes (16/21 of the items) and then beds (7/21 of the items). The bed colors could be chosen depending on the seed.

The things which don't drop anything usually contain one of the following 2 sets of 3 lines, and in any datapack they can be found by simply ordering the files by size and opening the smallest files. I think the game would be more fun if you knew for sure that everything drops something, though you might just not have the right tool for the job (i.e. silktouch, looting for low drop change, fortune for blocks, etc.).

```
{
  "type": "minecraft:block"
}
```

```
{
  "type": "minecraft:entity"
}
```

To add the beds as a drop, use the following code, which shows how to drop a white bed:
```
{
  "type": "minecraft:gift",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:white_bed"
        }
      ]
    }
  ]
}
```

I also think you should also generate a file containing all the transformations using the names of the files, both for debugging and for people to be able to look something up if it's actually unobtainable because it's part of a loop which cannot be found and cannot be crafted because at least one of the items needed can only be obtained from that very same loop. Here is a small example of the possible file contents:

```
cow > dog
dog > grass_block
dirt > stripped oak wood
grass_block > bed
ice > tripwire
tripwire > cow
stripped oak wood > ice
stone > shulker box
```

**Comment by Fasguy** [comment]
Just in case anyone stumbles upon this repository in the future:
This project isn't being maintained anymore and has been superseded by [Fasguy/MinecraftToolbox](https://github.com/Fasguy/MinecraftToolbox), which has addressed the issues described above.
